name: CI Test

on: 
  push: 
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get current path
      run: pwd
    - name: List files one lvl down
      working-directory: ./../
      run: ls -al
    - name: List files two lvl down
      working-directory: ./../../
      run: ls -al
#    - name: Install node dependencies
 #     working-directory: ./
  #    run: npm install
   # - name: Install composer dependencies
    #  working-directory: ./
     # run: composer install --no-dev --no-scripts
    #- name: Build assets
     # working-directory: ./
      #run: npm run build
    #- name: List files
     # working-directory: ./
      #run: ls -al
      
