# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install NPM packages
    - name: Install NPM packages
      run: npm install
      
    # Install composer packages
    - name: Install composer packages
      run:   composer install --no-dev --no-scripts
      
    # Build assets
    - name: Build assets
      run: npm run build
      
    # List all files
    - name: List all files
      run: ls -al
      
    - name: List theme files
      run: |
        cd wp-content/themes/eighshift-task
        ls -al
        
  # This workflow contains a single job called "deploy"
  #deploy:
   # runs-on: ubuntu-latest

    #steps:
      #- uses: BuildPC/rsync-with-ssh-github-actions@master
        #env:
          #HELLO: cool
          #MESSAGE: hello world
        #with:
          #key: ${{ secrets.SSH_KEY }}
          #host: example.com
          #port: 22
          #user: john
          #destination: /var/www/
          ## runs this on remove server
          #ssh_before: |
            #echo $HELLO
            #echo $MESSAGE
            #ls -lath

          ## then run these commands
          #ssh_after: |
            #echo $HELLO
            #echo $MESSAGE
            #ls -lath
