name: CI Test

on: 
  push: 
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - working-directory: ./
    - name: List files
      run: ls -al
    - name: Install node dependencies
      run: npm install
    - name: Install composer dependencies
      run: composer install --no-dev --no-scripts
    - name: Build assets
      run: npm run build
    - name: List files
      run: ls -al
      
