name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm install, build, and test
      run: |
        pwd
        ls -al
        npm install
        composer install --no-dev --no-scripts
        npm run build
        ls -al
      env:
        CI: true
